version: '3.9'
services:
  # Postgres DB
  postgres-db:
    container_name: database-app
    image: postgres:15
    ports:
      - '5432:5432' # 포트 변경 가능
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

  
  # spring boot application
  discodeit:
    container_name: discodeit-app
    build: .
    image: discodeit:local # 이미지 이름
    ports:
      - '8081:80'
    networks:
      - backend
    volumes:
      - app-storage:/app/.discodeit # 파일 저장소 경로랑 동일
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      DISCODEIT_STORAGE_LOCAL_ROOT-PATH: .discodeit # 파일 저장소 경로
    env_file:
      - .env
    depends_on:
      - postgres-db

# 네트워크 설정(기본으로 같은 네트워크에 생성되기 때문에 생략가능)
networks:
  backend:
    driver: bridge # default, 생략 가능

# 볼륨 설정
volumes:
  db-data:
  app-storage: